### ISSUE TITLE
add beautify-on-save functionality

### ISSUE THREAD

**Issue by garretwilson** [babobski/Beautify-js#1]
Please add an option to beautify each time the file is saved.

I realize that at http://komodoide.com/packages/addons/beautify-js/ you have provided a programmer-oriented workaround for adding this functionality on a per-installation basis, but it is not viable for deployment to non-programmer authors who are e.g. doing internationalization.

I'm curious as to why you provided that intricate workaround rather than implementing it in the plugin to begin with, as e.g. is done in the atom-beautify plugin. Is there some limitation to the Komodo plugin architecture that prevents this option from being bundled into the add-on, with a simple checkbox to turn on or off? Or did you simply not have time? Thanks for any feedback, as I'm considering plugin development for Komodo or Atom myself, and I need to know about any limitations of one versus the other.

**Comment by babobski** [comment]
Currently I don't see much in a on save functionality, the beautify js addon only work's with html, css and javascript files. For html it doesn't support multiple languages, i think the beautifier needs to be more robust for that kind of function to be reliable enough to be integrated to the addon.

I created the userscript so if someone really want's that functionality, the they have a head start in creating a userscipt that does that for them.

As for for  the komodo api there is no limitation to craft that kind of function and create the ability to toggle it true the settings of the addon.
