### ISSUE TITLE
add easy way to bind keymap

### ISSUE THREAD

**Issue by garretwilson** [babobski/Beautify-js#2]
Please provide some default key bound to the beautifier.

I realize that at http://komodoide.com/packages/addons/beautify-js/ you have provided a programmer-oriented workaround for adding this functionality on a per-installation basis, but it is not viable for deployment to non-programmer authors who are e.g. doing internationalization.

I'm curious as to why you provided that intricate workaround rather than implementing it in the plugin to begin with, as e.g. is done in the atom-beautify plugin. Is there some limitation to the Komodo plugin architecture that prevents a key mapping from being bundled into the add-on? Or at least the plugin should provide something that would appear in the keymap UI in Komodo that I could easily bind keys to without adding code. Again is there some limitation in Komodo that prevents this from simply showing up as something I can bind keys to in the UI?

**Comment by babobski** [comment]
It's possible to set up key bindings for the addon functions, this will add the ability to set up key bindings true the preferences menu (preferences > key bindings). As this is a small feature to implement, this will be added soon.

**Comment by babobski** [comment]
Added the options to set the key bindings true the preferences, fixed in [commit](https://github.com/babobski/Beautify-js/commit/7d93a770963604269a6268c7dd11dee662d560fa)
